json:
  team: 
    key: api_name
    type: string
  email:
    key: api_email
    type: string 
  country: 
    key: api_country
    type: string 
  website: 
    key: api_website
    type: array 
xml:
  team: 
    key: api_name
    type: string
  email:
    key: api_email
    type: string 
  country: 
    key: api_country
    type: string 
  website: 
    key: api_website
    type: array 